name: Deploy

on:
  push:
    branches: ["canary"]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build -t ${{ github.repository }} .
      - name: Deploy image
        run: |
          docker stop ${{ github.event.repository.name }} || true
          docker rm ${{ github.event.repository.name }} || true
          docker run -d -e "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" -e "DATABASE_URL=${{ secrets.DATABASE_URL }}" --restart always --name ${{ github.event.repository.name }} ${{ github.repository }}
